# Generated by Django 5.2 on 2025-04-29 22:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontuei', '0002_jogador_atualizado_jogador_criado_sala_atualizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPontuacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pontuacao', models.PositiveIntegerField()),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pontuei.jogador')),
            ],
        ),
    ]
