# Generated by Django 5.2 on 2025-04-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontuei', '0003_historicopontuacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='cor',
            field=models.CharField(max_length=31),
        ),
    ]
